name: Main Branch

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/TypeCaster
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/TypeCaster
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/TypeCaster.UnitTests
    - name: Publish TypeCaster
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/TypeCaster/TypeCaster.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
